[seaweedfs:children]
masters
volumes
filers
s3gws

[masters]
node1 ansible_host=10.0.1.11
node2 ansible_host=10.0.1.12
node3 ansible_host=10.0.1.13

[volumes]
node1 ansible_host=10.0.1.11 rack=rack1
node2 ansible_host=10.0.1.12 rack=rack2
node3 ansible_host=10.0.1.13 rack=rack3

[filers]
node1 ansible_host=10.0.1.11
node2 ansible_host=10.0.1.12
node3 ansible_host=10.0.1.13

[s3gws]
node1 ansible_host=10.0.1.11
node2 ansible_host=10.0.1.12
node3 ansible_host=10.0.1.13

[monitor]
monitor ansible_host=10.0.0.2

[backup]
backup ansible_host=10.0.0.4
