---
- name: 配置 Volume systemd service
  template:
    src: seaweedfs-volume.service.j2
    dest: /etc/systemd/system/seaweedfs-volume.service
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart seaweedfs-volume

- name: 启动并启用 Volume 服务
  systemd:
    name: seaweedfs-volume
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
